### PR TITLE
use node-ip-address as metallb-speaker-peer

### PR DESCRIPTION
**Pull request by mwennrich**
Currently metal-ccm detects the address where metallb should talk to for bgp announcements from worker node labels:

```
CalicoIPv4IPIPTunnelAddr  = "projectcalico.org/IPv4IPIPTunnelAddr"
CalicoIPv4VXLANTunnelAddr = "projectcalico.org/IPv4VXLANTunnelAddr"
```

The depend on the calico to be configured in VXLAN mode. Our goal is to run calico in "backend=none" mode, therefor we must change the nodeip detection as shown here.

TODO:

- [x] check if bpgd on the worker node still accepts announcements on the new ip.

### CODE REVIEW

**Comment by majst01** [comment]
unsure if frr will accept updates coming on this address

**Comment by mwennrich** [comment]
iirc, I did test this, but we surely have to test this again

**Comment by majst01** [comment]
we should put this together into the next release i try to implement a fix for #42 as well

**Comment by majst01** [comment]
After this is merged we can also remove the node tags:

```
	CalicoIPv4IPIPTunnelAddr  = "projectcalico.org/IPv4IPIPTunnelAddr"
	CalicoIPv4VXLANTunnelAddr = "projectcalico.org/IPv4VXLANTunnelAddr"
```

**Comment by Gerrit91** [comment]
Can there be a traffic interrupt when migrating to this new MetalLB config?

**Comment by mwennrich** [comment]
> Can there be a traffic interrupt when migrating to this new MetalLB config?

Absolutely, yes. BGP-Session will be dropped and restarted again. But interruption should be within seconds ... how long it takes to start a speaker-pod.

**Comment by Gerrit91** [comment]
Ok. Then I am assuming that the rolling update and the config adaption does not happen synchronously.

So, first the metal-ccm will be rolled out, adapts the `config` and causes on all speaker pods because the BGP will be re-established. Then, we do the rolling update and the speaker pods "may" cause another interruption, too.

**Comment by mwennrich** [comment]
Ok, did test it again ... there is no restart involved, the configmap change is detected and bgp is soft-reloaded:

```
controller-57dc9bdd7c-wmq4q controller {"caller":"main.go:100","configmap":"metallb-system/config","event":"startUpdate","msg":"start of config update","ts":"2022-01-12T13:40:00.30019138Z"}
speaker-cpblg speaker {"caller":"main.go:330","configmap":"metallb-system/config","event":"startUpdate","msg":"start of config update","ts":"2022-01-12T13:40:00.300699654Z"}
controller-57dc9bdd7c-wmq4q controller {"caller":"main.go:113","configmap":"metallb-system/config","event":"endUpdate","msg":"end of config update","ts":"2022-01-12T13:40:00.300272569Z"}
controller-57dc9bdd7c-wmq4q controller {"caller":"k8s.go:544","configmap":"metallb-system/config","event":"configLoaded","msg":"config (re)loaded","ts":"2022-01-12T13:40:00.300289642Z"}
speaker-cpblg speaker {"caller":"bgp_controller.go:75","configmap":"metallb-system/config","event":"peerRemoved","msg":"peer deconfigured, closing BGP session","peer":"10.244.235.26","reason":"removedFromConfig","ts":"2022-01-12T13:40:00.300986603Z"}
speaker-cpblg speaker {"caller":"bgp_controller.go:189","configmap":"metallb-system/config","event":"peerAdded","msg":"peer configured, starting BGP session","peer":"10.128.88.2","ts":"2022-01-12T13:40:00.301175844Z"}
speaker-cpblg speaker {"caller":"main.go:354","configmap":"metallb-system/config","event":"endUpdate","msg":"end of config update","ts":"2022-01-12T13:40:00.301325913Z"}

```

So there is virtually no real downtime. FRR on the firewall:

```
Jan 12 14:40:00 shoot--pd76mr--inttest0-firewall-7c54a bgpd[815]: Tx route delete VRF 9 212.34.83.15/32
Jan 12 14:40:00 shoot--pd76mr--inttest0-firewall-7c54a bgpd[815]: Tx route add VRF 9 212.34.83.15/32 metric 0 tag 0 count 2
```

**Review by Gerrit91 — APPROVED** [review]

**Pull request merged**
