### PR TITLE
Only auto-assign IPs in default external network.

### LINKED ISSUE #18: CCM configures all external networks with IP auto-assignment for metalLB
Not fully sure if this a real issue at the moment, but we saw that during Kubernetes cluster creation the kube-apiserver was getting an IP address of an external network that has no internet connectivity. This prevented the cluster from coming up.

I would assume that only the default external network should have enabled IP auto-assigment for MetalLB?

### PR DESCRIPTION
**Pull request by Gerrit91**
Closes #18.

### CODE REVIEW

**Review by mwennrich — APPROVED** [review]
lgtm

**Comment by Gerrit91** [comment]
Before:

```
k describe cm
Name:         config
Namespace:    metallb-system
...

Data
====
config:
----
address-pools:
- addresses:
  - 10.127.0.1/32
  auto-assign: true
  name: storage-fra-equ01-ephemeral
  protocol: bgp
- addresses:
  - 212.34.83.13/32
  - 212.34.83.12/32
  - 212.34.83.21/32
  - 212.34.83.3/32
  auto-assign: true
  name: internet-ephemeral
  protocol: bgp
...
``` 

After:

``` 
...
Data
====
config:
----
address-pools:                                                                                                                                                                                                     
- addresses:                                                                                                                                                                                                       
  - 10.127.0.1/32                                                                                                                                                                                                  
  auto-assign: false
  name: storage-fra-equ01-ephemeral
  protocol: bgp
- addresses:
  - 212.34.83.13/32
  - 212.34.83.12/32
  - 212.34.83.21/32
  - 212.34.83.3/32
  auto-assign: true
  name: internet-ephemeral
  protocol: bgp
...
```

**Review by majst01 — APPROVED** [review]
Requires changes to gepm on how metal-ccm is deployed.

**Comment by Gerrit91** [comment]
Requires changes? I don't think so, we are passing the default external network since the last release already?

**Comment by majst01** [comment]
a great, sorry for confusion

**Pull request merged**
