### PR TITLE
Remove legacy

### PR DESCRIPTION
**Pull request by majst01**

### CODE REVIEW

**Comment by Gerrit91** [comment]
Maybe the OpenStack code can help us to initialize the CCM properly: https://github.com/kubernetes/cloud-provider-openstack/blob/master/cmd/openstack-cloud-controller-manager/main.go

**Comment by majst01** [comment]
Sample PR for the equinix metal ccm doing the same: https://github.com/equinix/cloud-provider-equinix-metal/pull/185

**Comment by majst01** [comment]
```
cloud-controller-manager-7b5b85b9c8-lqw7s cloud-controller-manager F0920 06:21:39.543628       1 main.go:72] no ClusterID found.  A ClusterID is required for the cloud provider to function properly.  This check can be bypassed by setting the allow-untagged-cloud option

```

**Comment by majst01** [comment]
Now starts in test

**Review by Gerrit91 — APPROVED** [review]

**Comment by majst01** [comment]
Actual error on cluster create:

```
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager I0928 13:33:12.847534       1 log.go:184] metal-ccm housekeeping | tags syncher failed: failed to list nodes: nodes is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot li
st resource "nodes" in API group "" at the cluster scope                                                                                                                                                                                                                        
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager I0928 13:33:12.847820       1 log.go:184] metal-ccm housekeeping | metallb syncher failed: error listing nodes: failed to list nodes: nodes is forbidden: User "system:serviceaccount:kube-system:cloud-contr
oller-manager" cannot list resource "nodes" in API group "" at the cluster scope                                                                                                                                                                                                
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager E0928 13:33:12.847966       1 reflector.go:138] k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kub
e-system:cloud-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope                                                                                                                                                                            
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager I0928 13:33:12.916036       1 shared_informer.go:247] Caches are synced for service                                                                                                                          
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager E0928 13:33:13.660494       1 reflector.go:138] k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kub
e-system:cloud-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope                                                                                                                                                                            
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager E0928 13:33:15.276529       1 reflector.go:138] k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kub
e-system:cloud-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope                                                                                                                                                                            
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager E0928 13:33:20.615199       1 reflector.go:138] k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kub
e-system:cloud-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope                                                                                                                                                                            
cloud-controller-manager-5d98854ccc-x6rfv cloud-controller-manager E0928 13:33:30.302908       1 reflector.go:138] k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kub
e-system:cloud-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope


```

**Review by mwennrich — APPROVED** [review]

**Pull request merged**
